### ISSUE TITLE
[gltf, custom model] Vertex Colors 'read past end of archive' crash

### ISSUE THREAD

**Issue by RexTheWho** [kythyria/payday2-model-tool#1]
Using Vertex Colors from blender causes this crash:
```
Application has crashed: C++ exception
Archive::checked_read() Attempt to read past end of archive
```

Note, if vertex coloring works one side of the pool tiles should turn black, the other half visible.
If the entire pool tile section is black the object is missing its coloring.

'Maxico' test level, contains Blend files for working version, version with vertex colors and version with multiple materials.
`Maps\maxico\assets\units\pd2_mod_maxman\mansion_ext`
[maxico_report.zip](https://github.com/kythyria/payday2-model-tool/files/4111673/maxico_report.zip)

**Comment by kythyria** [comment]
Fixed in 52a35f7
