### ISSUE TITLE
Model tool failed to convert my file.

### ISSUE THREAD

**Issue by MiamiCenterPL** [kythyria/payday2-model-tool#13]
Here's my logs;
`Status: NewModel.Execute: Creating new model
Status: CreateNewObjects.Execute: New objects will be created
Status: Import.Execute: Importing from D:\PAYDAY 2 Model stuff\MODEL PARSER\bridge_ext.glb
Warn: ImportPanel.convert_Click: Exception generating Diesel file: SharpGLTF.Validation.DataException: Accessor[13] Accessor[13][0] is not of unit length: 0.
   w SharpGLTF.Schema2.ModelRoot.ReadGLB(Stream stream, ReadSettings settings)
   w SharpGLTF.Schema2.ModelRoot.Load(String filePath)
   w PD2ModelParser.Importers.GltfImporter.Import(FullModelData fmd, String path, Boolean createModels, Func`2 parentFinder, IOptionReceiver _) w C:\projects\payday2-model-tool\PD2ModelParser\Importers\GltfImporter.cs:wiersz 23
   w PD2ModelParser.FileTypeInfo.GltfType.Import(FullModelData data, String path, Boolean createModels, Func`2 parentFinder, IOptionReceiver options) w C:\projects\payday2-model-tool\PD2ModelParser\Filetype.cs:wiersz 64
   w PD2ModelParser.Modelscript.Import.Execute(ScriptState state) w C:\projects\payday2-model-tool\PD2ModelParser\Modelscript\ScriptCommands.cs:wiersz 141
   w PD2ModelParser.Modelscript.ScriptState.ExecuteItems(IEnumerable`1 items) w C:\projects\payday2-model-tool\PD2ModelParser\Modelscript\Script.cs:wiersz 407
   w PD2ModelParser.Modelscript.Script.ExecuteItems(IEnumerable`1 items, String workDir, FullModelData initialModel) w C:\projects\payday2-model-tool\PD2ModelParser\Modelscript\Script.cs:wiersz 53
   w PD2ModelParser.UI.ImportPanel.convert_Click(Object sender, EventArgs e) w C:\projects\payday2-model-tool\PD2ModelParser\UI\ImportPanel.cs:wiersz 175`
*wiersz means line*
The .glb file and .blend file; https://www.dropbox.com/s/3hyegn1g171fh81/BLEND.zip?dl=0

**Comment by kythyria** [comment]
Unfortunately I can't do anything about that error except maybe make it clearer when it happens: It results from bogus normal-related data (as the [official validator](http://github.khronos.org/glTF-Validator/) is able to point out). I'm not sure why Blender does that sometimes, alas.

**Comment by MiamiCenterPL** [comment]
Alright then. If nothing can be done with it, then I'll simply don't use the Harden Normals method (Which caused this issue)
