### ISSUE TITLE
[gltf, custom model] Multiple materials on single object issue

### ISSUE THREAD

**Issue by RexTheWho** [kythyria/payday2-model-tool#3]
Multiple materials apply, but verts are misplaced.
![image](https://user-images.githubusercontent.com/26837908/73117309-6ae45700-3f7e-11ea-88c4-61393f3cecd6.png)

'Maxico' test level, contains Blend files for working version, version with vertex colors and version with multiple materials.
`Maps\maxico\assets\units\pd2_mod_maxman\mansion_ext`
[maxico_report.zip](https://github.com/kythyria/payday2-model-tool/files/4111673/maxico_report.zip)

**Comment by kythyria** [comment]
Seems to be fixed in c803ffd.
