### ISSUE TITLE
[gltf export] Can't extract 'large' model

### ISSUE THREAD

**Issue by Dushess** [kythyria/payday2-model-tool#6]
If 106kB is can be even considered as large.
![766](https://user-images.githubusercontent.com/15954961/74124792-90ab6600-4be4-11ea-99d4-218b416a2f68.png)

**Comment by Dushess** [comment]
BUT, this was good and no questions (509kB)
bnk_int_vault_big_bank.model

**Comment by kythyria** [comment]
It's not size that's the issue; AFAIK there's nothing that you can have less of in GLTF than in Diesel models. It looks like the cause of that crash is nonsensical binormal vectors, which as of 50b2769
no longer cause crashes (it arbitrarily picks one of the two possible meaningful binormals).

**Comment by Dushess** [comment]
It works, but there's a problem, another one. 
![64](https://user-images.githubusercontent.com/15954961/74431083-4b4e9900-4e6f-11ea-8b2d-3a62e1b0e762.png)

**Comment by kythyria** [comment]
What file is that?

**EDIT**: It looks like `units\pd2_dlc_brb\architecture\brb_int\brb_int_main_building`, which works fine for me.

**Comment by Dushess** [comment]
I'm pretty late, this is base points floating from original positions. Short desctiption: every unit part is on right the same point, even if designed to be in 3 different places.
