### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by polarathene** [kythyria/payday2-model-tool#9]
Is it possible to use this via a command-line interface? I would like to batch export to gltf.

**Comment by kythyria** [comment]
Yes. As of 1712da2d it knows about GLTF too. Run it with `--help` to see the options. For export, `--load=foo.model --export=foo.gltf`. Repeat as many times as you have models (up to the OS limit on command line lengths, anyway).

The model tool is quite slow to start, so repeating `--load` and `--export` is preferable to multiple invocations as far as speed goes.

**Comment by ImUrX** [comment]
thanks for solving this https://gfycat.com/RecklessFondFalcon
